name: Train
description: |
  Train a TRADE model
inputs:
  - {name: owner, description: ''}
  - {name: project, description: ''}
  - {name: experiment, description: ''}
  - {name: model, description: ''}
  - {name: s3_datadir, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '932360549041.dkr.ecr.us-west-2.amazonaws.com/trade-dst:20201111.2'
    command:
    - /bin/bash
    - -e
    - -c
    - |
      . k8s/lib.sh

      parse_args "$0" "owner project experiment model s3_datadir s3_model_dir" "$@"
      shift $n
      set -x

      aws s3 sync --no-progress ${s3_datadir} data/

      python3 myTrain.py -dec=TRADE -bsz=8 -dr=0.2 -lr=0.001 -le=1 $@

      S3_MODEL_DIR=s3://geniehai/${owner}/models/${project}/${experiment}/${model}/`date +%s`/
      aws s3 sync --no-progress save/ ${S3_MODEL_DIR}

      mkdir -p `dirname $s3_model_dir`
      echo ${S3_MODEL_DIR} > $s3_model_dir

    args: [
      'cmd',
      --owner, {inputValue: owner},
      --project, {inputValue: project},
      --experiment, {inputValue: experiment},
      --model, {inputValue: model},
      --s3_datadir, {inputValue: s3_datadir},
      --s3_model_dir, {outputPath: s3_model_dir},
      --,
      {inputValue: additional_args},
    ]
