name: Train
description: |
  Train a SimpleTOD model
inputs:
  - {name: owner, description: ''}
  - {name: project, description: ''}
  - {name: experiment, description: ''}
  - {name: model, description: ''}
  - {name: s3_datadir, description: ''}
  - {name: train_batch_size, description: ''}
  - {name: image, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '{{inputs.parameters.image}}'
    command:
    - /bin/bash
    - -e
    - -c
    - |
      . k8s/lib.sh

      parse_args "$0" "image owner project experiment model train_batch_size s3_datadir s3_model_dir" "$@"
      shift $n
      set -x

      aws s3 sync --no-progress ${s3_datadir} resources/
      mkdir -p "/shared/tensorboard/${project}/${experiment}/${owner}/${model}"
      ln -s "/shared/tensorboard/${project}/${experiment}/${owner}/${model}" "./runs"

      ./train_dst.sh 0 gpt2 distilgpt2 ${train_batch_size} $@
      
      S3_MODEL_DIR=s3://geniehai/${owner}/models/${project}/${experiment}/${model}/`date +%s`/
      aws s3 sync --no-progress output/ ${S3_MODEL_DIR}
      
      mkdir -p `dirname $s3_model_dir`
      echo ${S3_MODEL_DIR} > $s3_model_dir
      
      checkpoint=$(ls output/distilgpt2/ | grep -o '[0-9]*' | sort -nr | head -n1)
      python3 generate_dialogue.py --checkpoint ./output/distilgpt2/checkpoint-${checkpoint} --split_set test
      ls -al
      aws s3 cp --no-progress *.json ${S3_MODEL_DIR}
    
    args: [
      'cmd',
      --image, {inputValue: image},
      --owner, {inputValue: owner},
      --project, {inputValue: project},
      --experiment, {inputValue: experiment},
      --model, {inputValue: model},
      --s3_datadir, {inputValue: s3_datadir},
      --s3_model_dir, {outputPath: s3_model_dir},
      --,
      {inputValue: additional_args}, 
    ]