name: Train
description: |
  Train a SimpleTOD model
inputs:
  - {name: owner, description: ''}
  - {name: project, description: ''}
  - {name: experiment, description: ''}
  - {name: model, description: ''}
  - {name: s3_datadir, description: ''}
  - {name: additional_args, description: ''}
outputs:
  - {name: s3_model_dir}
implementation:
  container:
    image: '932360549041.dkr.ecr.us-west-2.amazonaws.com/simpletod:20201121.4'
    command:
    - /bin/bash
    - -e
    - -c
    - |
      . k8s/lib.sh

      parse_args "$0" "owner project experiment model s3_datadir s3_model_dir" "$@"
      shift $n
      set -x

      aws s3 sync --no-progress ${s3_datadir} resources/

      ./train_dst.sh 0 gpt2 distilgpt2 32
      
      S3_MODEL_DIR=s3://geniehai/${owner}/models/${project}/${experiment}/${model}/`date +%s`/
      aws s3 sync --no-progress output/ ${S3_MODEL_DIR}
      
      mkdir -p `dirname $s3_model_dir`
      echo ${S3_MODEL_DIR} > $s3_model_dir
      
      python3 generate_dialogue.py --checkpoint ./output/distilgpt2 --split_set test
      aws s3 cp --no-progress *.json ${S3_MODEL_DIR}
    
    args: [
      'cmd',
      --owner, {inputValue: owner},
      --project, {inputValue: project},
      --experiment, {inputValue: experiment},
      --model, {inputValue: model},
      --s3_datadir, {inputValue: s3_datadir},
      --s3_model_dir, {outputPath: s3_model_dir},
      --,
      {inputValue: additional_args}, 
    ]